### PR TITLE
Improve aesthetics of site & added README for docs

### PR DESCRIPTION
**Pull request by vinothchandar**
- Uses the Apache Hudi logo
 - Fixed topnav bg to be transparent to match logo
 - Adjusted font colors
 - Removed unsued icons
 - Added README with build instructions

### CODE REVIEW

**Comment by vinothchandar** [comment]
screen shot 2019-02-15 at 10 19 13 am

**Comment by tweise** [comment]
Consider using docker for building the site (I had sent you a link for that before). Having to install things on the host puts a higher barrier for contributors to make site updates and also tends to yield indeterministic results due to version mismatches.

**Comment by vinothchandar** [comment]
the template already supports docker. Instructions are in the detailed docs, linked off README.
That said, I updated some gem versions. So let me retest and push with docker based setup on README.

**Comment by tweise** [comment]
Great. I would recommend to put that into the README, instead if instructions how to install bits and pieces on the machine.

Also, you probably want a .gitignore and remove things like `docs/.DS_Store` from this PR.

**Comment by vinothchandar** [comment]
yeah looks like it sneaked in, since I had the server up when I committed locally. Anyways cleaned up now.

**Pull request merged**
